development:
  adapter: postgresql
  encoding: unicode
  database: fishpond
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: fishpond
  pool: 5
  username: halftoneapp
  password: ca5UHapH

test:
  adapter: postgresql
  encoding: unicode
  database: halftoneapp_test
  pool: 5
  username: halftoneapp
  password: ca5UHapH